name: Is Organization Member Example

on:
  issues:
    types: [opened, labeled]

jobs:
  is-member:
    name: Is org member?
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'opened'
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: railwayapp
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on issue for external
        if: |
          ${{ steps.is_organization_member.outputs.result != 'true' }}
        uses: alexrogalskiy/github-action-issue-commenter@master
        with:
          message: 'this issue was created by an external contributor'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
