name: Is Organization Member Example

on:
  issues:
    types: [opened, labeled]

jobs:
  is-member:
    name: Is org member?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Check if organization member
        id: is_organization_member
        uses: zuchka/community-actions@v1.1.6
        with:
          org: railwayapp
          username: zuchka
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment for external
        run: echo "${{ steps.is_organization_member.outputs.result}}"
